from . import ir_actions_server
from . import res_users
from . import velardi_telegram_config
from . import velardi_telegram_msg_automation
from . import res_partner
from . import velardi_telegram_notification
from . import velardi_telegram_mixin
from . import velardi_telegram_command
from . import velardi_telegram_user
from . import velardi_telegram_group